[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon_mumbai = "${POLYGON_MUMBAI_RPC_URL}"

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}", chain = 137 }
polygon_mumbai = { key = "${POLYGON_ETHERSCAN_API_KEY}", chain = 80001 }