[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon_mumbai = "${POLYGON_MUMBAI_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
avalanche_fuji = "${AVALANCHE_FUJI_RPC_URL}"

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
sepolia = { key = "${MAINNET_ETHERSCAN_API_KEY}", chain = 11155111 }
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}", chain = 137 }
polygon_mumbai = { key = "${POLYGON_ETHERSCAN_API_KEY}", chain = 80001 }
base = { key = "${BASE_ETHERSCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASE_ETHERSCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", chain = 42161, url = "https://api.arbiscan.io/api" }
arbitrum_sepolia = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", chain = 421614, url = "https://api-sepolia.arbiscan.io/api" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", chain = 10, url = "https://api-optimistic.etherscan.io/api" }
optimism_sepolia = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", chain = 11155420, url = "https://api-sepolia-optimistic.etherscan.io/api" }
bsc = { key = "${BSC_ETHERSCAN_API_KEY}", chain = 56, url = "https://api.bscscan.com/api" }
bsc_testnet = { key = "${BSC_ETHERSCAN_API_KEY}", chain = 97, url = "https://api-testnet.bscscan.com/api" }
avalanche = { key = "${AVALANCHE_ETHERSCAN_API_KEY}", chain = 43114, url = "https://api.snowtrace.io/api" }
avalanche_fuji = { key = "${AVALANCHE_ETHERSCAN_API_KEY}", chain = 43113, url = "https://api-fuji.snowtrace.io/api" }
